config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'events/upcoming', to: 'events#show_upcoming'
  get 'events/past', to: 'events#show_past'

  devise_for :users
  resources :users, only: %w[index show new,create]
  resources :events, only: %w[index show new create]

  resources :attendances

  resources :attendances do
    match '/join', to: 'attendances#join', via: :post, on: :collection
  end

  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/attendence.rb
class Attendence < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, :desc, :location, :date, presence: true

  belongs_to :creator, class_name: 'User'
  has_many :attendances, dependent: :destroy
  has_many :attendees, through: :attendances, source: :user

  scope :upcoming_events, -> { where('date >= ?', Date.today) }
  scope :past_events, -> { where('date < ?', Date.today) }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :email, presence: true

  has_many :created_events, class_name: 'Event', foreign_key: 'creator_id', dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :event_attended, through: :attendances, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def join
    @attendance = Attendance.new(event_id: params[:id], user_id: current_user.id)
    @attendance.save
    redirect_to events_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @events = Event.all
    @upcoming_events = Event.upcoming_events
    @past_events = Event.past_events
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event, notice: 'Your event was created'
    else
      render :new
    end
  end

  def show_upcoming
    @upcoming_events = Event.upcoming_events
  end

  def show_past
    @past_events = Event.past_events
  end

  private

  def event_params
    params.require(:event).permit(:title, :date, :location, :desc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    if signed_in?
      @created_events = current_user.created_events
      @attended_events = current_user.event_attended
    else
      redirect_to login_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    redirect_to users_path if @user.save
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_user_name(current_user)
    if signed_in?
      "<li class='nav-item'>
        <div class='nav-link text-white'>
          Logged in as [ <strong  >#{link_to current_user.name, user_path(current_user)} </strong>]
        </div>
      </li>
      <li class='nav-item'>
         #{link_to 'logout', destroy_user_session_path, class: 'nav-link text-white', method: :delete}
      </li>".html_safe
    else
      "<li class='nav-item'>
        #{link_to 'Log in / Sign up', new_user_registration_path, class: 'nav-link text-white'}
      </li>".html_safe
    end
  end

  def show_creator(event)
    if signed_in?
      "<h5 class='text-secondary'>Created by #{event.creator.name}</h5>".html_safe
    else
      "<h5 class='text-secondary'>Created by Anonymous</h5>".html_safe
    end
  end

  def show_attendees(attendees)
    result = '<p>No attendees yet</p>'
    unless attendees.count.zero?
      result = ''
      attendees.each do |attendee|
        result += "<div style='background-color: beige' class='rounded p-1 mb-1'>#{attendee.name}</div>"
      end
    end
    result.html_safe
  end

  def show_registration_button(event)
    if event.attendances.exists?(user_id: current_user.id)
      '<p>Already signed in</p>'.html_safe
    else
      (link_to 'Join', join_attendances_path(id: @event.id), class: 'btn btn-primary mb-4', method: :post).to_s.html_safe
    end
  end

  def show_create_event_button
    return unless current_user

    (link_to 'Create new event', new_event_path, class: 'nav-link text-info').to_s.html_safe
  end
end

app/views/events/_past_events.html.erb
<section class="container">
  <h1 class="text-center">Listing past events</h1>
  <div class='row'>
    <%@past_events and @past_events.each do |event| %>
      <div class="user_card card text-center m-2">
        <div class="card-header bg-dark text-white  ">
          <h2><%= event.title %></h2> 
          <%= show_creator(event) %>         
        </div>
        <div class="card-body">
          <p class="card-text"><%= event.desc %></p>
          <%= link_to 'Show more', event_path(event),class:'btn btn-primary' %>
        </div>
        <div class="card-footer text-white bg-dark">
          Created at <%= time_ago_in_words(event.created_at) %> ago
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/events/_upcoming_events.html.erb
<section class="container">
  <h1 class="text-center">Listing upcoming events</h1>
  <div class='row'>
    <%@upcoming_events and @upcoming_events.each do |event| %>
      <div class="user_card card text-center m-2">
        <div class="card-header bg-dark text-white  ">
          <h2><%= event.title %></h2> 
          <%= show_creator(event) %>         
        </div>
        <div class="card-body">
          <p class="card-text"><%= event.desc %></p>
          <%= link_to 'Show more', event_path(event),class:'btn btn-primary' %>
        </div>
        <div class="card-footer text-white bg-dark">
          Created at <%= time_ago_in_words(event.created_at) %> ago
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/events/index.html.erb
<%= render partial: 'past_events' %>
<%= render partial: 'upcoming_events' %>

app/views/events/new.html.erb
<section class='mt-5'>
  <%= form_with model: @event, local: true do |f| %>
    <% if @event.errors.any? %>
      <ul>
        <% @event.errors.full_messages.each do |error| %>
          <li> <%= error %> </li>
        <% end %>
      </ul>
    <% end %>
    <div class='m-auto col-6'>
      <div class="form-group d-flex align-items-center">
        <%= f.label :title,'Title:', class:'m-0 col-4 m-0 h3' %>
        <%= f.text_field :title, placeholder: "Event title", class: "form-control col-8"  %>
      </div>
      <div class="form-group d-flex align-items-center">
        <%= f.label :desc,'Description:', class:'m-0 col-4 m-0 h3' %>
        <%= f.text_area :desc, placeholder: "Event description", class: "form-control col-8"  %>
      </div>
      <div class="form-group d-flex align-items-center">
      <%= f.label :date,'Date:', class:'m-0 col-4 m-0 h3' %>
        <%= f.date_field :date, class: "form-control col-8"  %>
      </div>

    <div class="form-group d-flex align-items-center">
    <%= f.label :date,'Location:', class:'m-0 col-4 m-0 h3' %>
      <%= f.text_field :location, placeholder: "Event location", class: "form-control col-8"  %>
    </div>

    <%= f.submit class: "btn btn-outline-primary mt-3 ml-3" %>
    </div>

  <% end %>
</section>

app/views/events/show.html.erb
<section>
  <div class='d-flex align-items-center mt-4'>
    <p class='text-secondary m-0 mr-3 event_characteristics_width'>Event title :</p>
    <h1 class='font-weight-bold'><%= @event.title.titleize %></h1>
  </div>
  <div class='d-flex align-items-center'>
    <p class='text-secondary m-0 mr-3 event_characteristics_width'>Created by :</p>
    <h5 class='font-weight-bold mb-0'>
      <%= @event.creator.name %>
    </h5>
  </div>
  <div class='d-flex align-items-center'>
    <p class='text-secondary m-0 mr-3 event_characteristics_width'>Date :</p>
    <h5 class='font-weight-bold mb-0'><%= @event.date.strftime("%d %b, %Y at %l:%M %p") %></h5> 
  </div>
  <div class='d-flex align-items-center mb-4'>
    <p class='text-secondary m-0 mr-3 event_characteristics_width'>Location :</p>
    <h5 class='font-weight-bold mb-0'><%= @event.location %></h5>
  </div>
  <%= show_registration_button(@event) %>
  <div class="container">
    <div class="row justify-content-between">
      <div class="col-8 event_description">
        <h2>Description</h2>
        <p><%= @event.desc %></p>
      </div>
      <div class="col-3 event_description">
        <h2>Attendees</h2>
        <%= show_attendees(@attendees)  %>
      </div>
    </div>
  </div>
</section>

app/views/events/show_past.html.erb
<%= render partial: 'past_events' %>

app/views/events/show_upcoming.html.erb
<%= render partial: 'upcoming_events' %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-gradient-dark">
  <div class="container p-0">
    <h2 class='mr-3'>
      <i><%= link_to "Private Events", events_path,class:'text-white text-decoration-none' %></i>
    </h2>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Members', users_path, class: 'nav-link text-white' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Events
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Upcoming events', events_upcoming_path,class: 'dropdown-item nav-link' %>
            <%= link_to 'Past events', events_past_path,class: 'dropdown-item nav-link' %>
          </div>    
        </li>
        <li class="nav-item">
          <%= show_create_event_button %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
         <%= show_user_name(current_user) %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <main class='container p-0'>
      <%= render_flash_messages dismissible: true,class:'bg-primary text-white' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/index.html.erb
<section class="container">
  <div class='row'>
    <% @users.each do |user| %>
      <div class="user_card card text-center m-2">
        <div class="card-header">
          <h2><%= user.name %></h2>
          <h5><%= user.email %></h5>
        </div>
        <div class="card-body">
          <p>Created events - <%= user.created_events.count %> </p>
          <p>Joined events - <%= user.attendances.count %> </p>
        </div>
        <div class="card-footer text-muted">
          2 days ago
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/users/show.html.erb
<section class="container">
  <h1 class="text-center mt-4"><%= current_user.name %> created events</h1>
  <h4 class='my-4'>Created events - <%= @created_events.count %></h4>
  <div class='row'>
    <% @created_events.each do |event| %>
      <div class="user_card card text-center m-2">
        <div class="card-header bg-dark text-white  ">
          <h2><%= event.title %></h2>
          <%= show_creator(event) %>
        </div>
        <div class="card-body">
          <p class="card-text"><%= truncate(event.desc,length:20) %></p>
          <%= link_to 'Show more', event_path(event),class:'btn btn-primary' %>
        </div>
        <div class="card-footer text-white bg-dark">
          Created at <%= time_ago_in_words(event.created_at) %> ago
        </div>
      </div>
    <% end %>
  </div>

  <h4 class='my-4'>Attended events - <%= @attended_events.count %></h4>
  <div class='row'>
    <% @attended_events.each do |event| %>
      <div class="user_card card text-center m-2">
        <div class="card-header bg-dark text-white  ">
          <h2><%= event.title %></h2>
          <%= show_creator(event) %>
        </div>
        <div class="card-body">
          <p class="card-text"><%= truncate(event.desc,length:20) %></p>
          <%= link_to 'Show more', event_path(event),class:'btn btn-primary' %>
        </div>
        <div class="card-footer text-white bg-dark">
          Created at <%= time_ago_in_words(event.created_at) %> ago
        </div>
      </div>
    <% end %>
  </div>
 

</section>